# vtierp_project_custom/docker-compose.yml
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: vtierp_api_custom
    ports:
      - "8000:8000" # Host:Container
    volumes:
      - ./data:/app/data  # Persist data (uploads, vector stores) on host
      - ./app:/app/app # For development, mount app code for live reloading
    env_file:
      - .env # Load environment variables from .env file in the project root
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: vtierp_streamlit_custom
    ports:
      - "8501:8501" # Host:Container
    depends_on:
      - api # Ensures API starts before Streamlit
    volumes:
      - ./streamlit_ui:/app/streamlit_ui # For development, mount streamlit code for live reloading
    environment:
      - FASTAPI_URL=http://api:8000 # Service discovery within Docker network
    env_file:
      - .env # Can also pick up GOOGLE_API_KEY from here if needed by Streamlit directly
    restart: unless-stopped
